Задание 1

SELECT CUST_FIRST_NAME, CUST_LAST_NAME FROM SH.CUSTOMERS
WHERE CUST_CREDIT_LIMIT < 3000
AND CUST_GENDER = 'F' AND CUST_MARITAL_STATUS = 'married' AND COUNTRY_ID NOT IN ('JP', 'BR', 'IT')
ORDER BY CUST_LAST_NAME;


Задание 2

SELECT 'Name: ' || CUST_FIRST_NAME || ' ' || CUST_LAST_NAME || ' '
|| 'address: ' || CUST_STREET_ADDRESS || ' ' || 'number: ' || CUST_MAIN_PHONE_NUMBER || ' ' ||
'email: ' || CUST_EMAIL AS RESULT FROM (SELECT * FROM SH.CUSTOMERS WHERE CUST_MAIN_PHONE_NUMBER LIKE '%77' 
ORDER BY LENGTH(CUST_STREET_ADDRESS) DESC) WHERE ROWNUM < 2;


Задание 3

SELECT DISTINCT CUST_LAST_NAME, CUST_FIRST_NAME FROM SH.CUSTOMERS 
JOIN SH.SALES ON CUSTOMERS.CUST_ID = SALES.CUST_ID 
JOIN SH.PRODUCTS ON SALES.PROD_ID = PRODUCTS.PROD_ID
WHERE CUSTOMERS.CUST_YEAR_OF_BIRTH > 1980 
AND (PRODUCTS.PROD_SUBCATEGORY = 'Sportcoats%' OR PRODUCTS.PROD_SUBCATEGORY = 'Shoes - Boys') 
AND PRODUCTS.PROD_MIN_PRICE = (SELECT MIN(PROD_MIN_PRICE) FROM SH.CUSTOMERS 
JOIN SH.SALES ON CUSTOMERS.CUST_ID = SALES.CUST_ID 
JOIN SH.PRODUCTS ON SALES.PROD_ID = PRODUCTS.PROD_ID
WHERE (PROD_SUBCATEGORY = 'Sportcoats%' OR PROD_SUBCATEGORY = 'Shoes - Boys') 
AND  CUSTOMERS.CUST_YEAR_OF_BIRTH > 1980);


Задание 4

SELECT * FROM SH.CUSTOMERS 
WHERE EXISTS 
(SELECT * FROM SH.COUNTRIES 
WHERE (COUNTRY_NAME IN ('United States of America', 'Germany')) 
AND CUST_GENDER = 'M'
AND CUST_INCOME_LEVEL LIKE 'D%'
AND CUST_MARITAL_STATUS IS NULL
AND CUSTOMERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID)
ORDER BY CUST_ID; 


Задание 5

SELECT COUNTRY_NAME, ROUND(AVG(AMOUNT_SOLD * QUANTITY_SOLD), 0) 
AS SOLD_AVG FROM SH.SALES 
INNER JOIN SH.CUSTOMERS ON SALES.CUST_ID = CUSTOMERS.CUST_ID 
INNER JOIN SH.COUNTRIES ON CUSTOMERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
GROUP BY COUNTRY_NAME ORDER BY SOLD_AVG DESC;


Задание 6

SELECT DOMAIN, COUNT(DOMAIN) FROM (SELECT SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@')) 
AS DOMAIN FROM SH.CUSTOMERS) 
GROUP BY DOMAIN ORDER BY DOMAIN; 


Задание 7

SELECT COUNTRY_NAME, TOTAL FROM 
(SELECT ROUND(SUM(QUANTITY_SOLD), 0) TOTAL, COUNTRY_NAME, ROUND(AVG(AMOUNT_SOLD)) CNT_AVG FROM SH.SALES
INNER JOIN SH.CUSTOMERS ON SALES.CUST_ID = CUSTOMERS.CUST_ID 
INNER JOIN SH.COUNTRIES ON COUNTRIES.COUNTRY_ID = CUSTOMERS.COUNTRY_ID 
INNER JOIN SH.PRODUCTS ON PRODUCTS.PROD_ID = SALES.PROD_ID
WHERE PRODUCTS.PROD_CATEGORY = 'Men' 
GROUP BY COUNTRY_NAME HAVING ROUND(SUM(QUANTITY_SOLD), 0) > ROUND(AVG(AMOUNT_SOLD), 0)) 
ORDER BY COUNTRY_NAME;


Задание 8

WITH TABLE_MEN AS
(SELECT COUNTRIES.COUNTRY_NAME, COUNT(CUSTOMERS.CUST_GENDER) AS MEN FROM SH.CUSTOMERS 
LEFT OUTER JOIN SH.COUNTRIES 
ON CUSTOMERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID 
WHERE CUST_GENDER = 'M' 
GROUP BY COUNTRY_NAME 
ORDER BY COUNTRY_NAME),
TABLE_WOMEN AS 
(SELECT COUNTRIES.COUNTRY_NAME, COUNT(CUSTOMERS.CUST_GENDER) AS WOMEN FROM SH.CUSTOMERS 
LEFT OUTER JOIN SH.COUNTRIES
ON CUSTOMERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID 
WHERE CUST_GENDER = 'F' 
GROUP BY COUNTRY_NAME 
ORDER BY COUNTRY_NAME)
SELECT TABLE_MEN.COUNTRY_NAME as "Страна", TRUNC(ROUND(TABLE_MEN.MEN * 100 / (TABLE_MEN.MEN + TABLE_WOMEN.WOMEN))) "% мужчин",
TRUNC(ROUND(TABLE_WOMEN.WOMEN * 100 / (TABLE_MEN.MEN + TABLE_WOMEN.WOMEN))) "% женщин" FROM TABLE_MEN 
LEFT OUTER JOIN TABLE_WOMEN 
ON TABLE_MEN.COUNTRY_NAME = TABLE_WOMEN.COUNTRY_NAME;

    
Задание 9

SELECT QS || ' / '|| SLS.TMD AS "Макс покуп/день", PROD.PROD_NAME FROM SH.PRODUCTS PROD 
JOIN (SELECT TRUNC(TIME_ID) TMD, SUM(QUANTITY_SOLD) QS, PROD_ID FROM SH.SALES 
GROUP BY TRUNC(TIME_ID),PROD_ID) SLS ON SLS.PROD_ID = PROD.PROD_ID 
WHERE ROWNUM < 21 
ORDER BY QS DESC;


Задание 10

WITH T1 AS (SELECT PROD_ID, TIME_ID, QUANTITY_SOLD FROM SH.SALES),
T2 AS (SELECT PROD_ID, PROD_CATEGORY FROM SH.PRODUCTS)
SELECT SUM(T1.QUANTITY_SOLD), T2.PROD_CATEGORY FROM T1 
LEFT OUTER JOIN T2 ON T1.PROD_ID = T2.PROD_ID 
GROUP BY T1.TIME_ID, T1.PROD_ID, T2.PROD_CATEGORY;


Задание 11

CREATE TABLE SALES_USER_ALEXANDER_AVILOV AS (SELECT * FROM SH.SALES
WHERE TRUNC(TIME_ID, 'month') = (WITH FT AS (SELECT COUNT(AMOUNT_SOLD) FAS, TRUNC(TIME_ID, 'month') FTI
FROM SH.SALES GROUP BY TRUNC(TIME_ID, 'month')), ST AS (SELECT MAX(COUNT(AMOUNT_SOLD)) SAS FROM SH.SALES 
GROUP BY TRUNC(TIME_ID, 'month')) SELECT FT.FTI FROM FT JOIN ST ON FT.FAS = ST.SAS));

COMMIT;



Задание 12

SELECT PROD_ID, CUST_ID, TO_CHAR(TIME_ID, 'DD.MM.YYYY HH24:MI:SS') TIME_ID, CHANNEL_ID, PROMO_ID, QUANTITY_SOLD, AMOUNT_SOLD 
FROM  SALES_USER_ALEXANDER_AVILOV 
ORDER BY TIME_ID;

COMMIT;


Задание 13

SELECT COUNT(AMOUNT_SOLD), TO_CHAR(TRUNC(TIME_ID, 'HH24'), 'DD.MM.YYYY HH24:MI:SS') TIME_ID   
FROM SALES_USER_ALEXANDER_AVILOV 
GROUP BY TRUNC(TIME_ID, 'HH24') 
ORDER BY TIME_ID;


Задание 14

DROP TABLE SALES_USER_ALEXANDER_AVILOV;

COMMIT;
